% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Sep-2019 13:46:35
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
saveVarsMat = load('kp6kd006Variaveis_PD_Alailson.mat');

NivelRefe = saveVarsMat.NivelRefe; % <50001x3 double> too many elements

Sat = saveVarsMat.Sat; % <50001x3 double> too many elements

ganhos = saveVarsMat.ganhos; % <50001x4 double> too many elements

clear saveVarsMat;
